references:
  container_config_node12: &container_config_node12
      working_directory: ~/project/build
      docker:
        - image: circleci/node:12-browsers
  workspace_root: &workspace_root
    ~/project
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root
version: 1
jobs:
  build:
    <<: *container_config_node12
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - build
  test:
    <<: *container_config_node12
    steps:
      - *attach_workspace
      - run: 
          name: Run tests
          command: npm test
workflows:
  version: 1
  build-and-test:
    jobs:
      - build
      - test